name: build

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ruby-version:
          - 3.0.0
          - 2.7.2
          - 2.6.6
          - 2.5.8
          - 2.4.10

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
